server:
  port: 10910
  servlet:
    context-path: /wse-accounts

spring:
  application:
    name: wse-accounts
  datasource:
    url: jdbc:h2:mem:account
    username: sa
    password: password
    driverClassName: org.h2.Driver
  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  h2:
    console.enabled: true

logging:
  file:
    name: accounts-service.log
  pattern:
    console: "%-4relative [%thread] %-5level %logger{35} CorrelationId -- %X{correlationId} --- %msg %n"
    file: "%-4relative [%thread] %-5level %logger{35} CorrelationId -- %X{correlationId} --- %msg %n"
  level:
    root: DEBUG