server:
  port: 10910

spring:
  datasource:
    url: jdbc:h2:mem:account
    username: sa
    password: password
    driverClassName: org.h2.Driver
  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true
    show-sql: true
    properties:
      hibernate:
        format_sql:true
  h2:
    console.enabled: true